/*
 * ClientJFrame.java
 *
 * Created on 25 July 2001, 01:52
 */

package jfreerails.client;
import javax.swing.JTable;
//import jfreerails.experimental.TestTable;
import jfreerails.lib.TextMessageHandler;

/**
 *
 * @author  Luke Lindsay
 */
public class ClientJFrame extends javax.swing.JFrame  implements jfreerails.client.MessengerBoy  {

   private javax.swing.JTable mainViewJTable;
          
    /** Creates new form ClientJFrame */
    public ClientJFrame(JTable jTable1) {
        TextMessageHandler.setMessengerBoy(this); 
        this.mainViewJTable=jTable1;
        System.out.println( "\nCreating client window" );
        initComponents();
    }
    /*
    public ClientJFrame() {
             TextMessageHandler.setMessengerBoy(this); 
        TestTable testTable=new TestTable();
        this.mainViewJTable=testTable.getJTable();
        System.out.println( "\nCreating client window" );
        initComponents();
    }
     */


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        messageBoyJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        messageBoyJLabel.setText("Welcome to freerails.  Use the mouse to lay track.  Moving the cursor by one square lays track");
        getContentPane().add(messageBoyJLabel, java.awt.BorderLayout.SOUTH);
        
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.add( mainViewJTable );
        jScrollPane1.setViewportView(jPanel1);
        
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    /*
    public static void main(String args[]) {
        new ClientJFrame().show();
    }
     */

    public void displayMessage(java.lang.String message) {
        messageBoyJLabel.setText(message);
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messageBoyJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
