/*
 * StationView.java
 *
 * Created on 15 October 2002, 21:22
 */

package jfreerails.client.top;

/**
 *
 * @author  Luke Lindsay
 */
public class StationView extends javax.swing.JDialog {

    /** Creates new form StationView */
    public StationView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\eclipse\\workspace\\CVSFreerails\\src\\jfreerails\\data\\station.gif"));
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);
        
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, java.awt.BorderLayout.NORTH);
        
        pack();
    }//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new StationView(new javax.swing.JFrame(), true).show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
