/*
 * ProgressJPanel.java
 *
 * Created on 08 September 2003, 20:48
 */

package jfreerails;
import jfreerails.util.FreerailsProgressMonitor;

/**
 *
 * @author  Luke Lindsay
 */
public class ProgressJPanel extends javax.swing.JPanel {
    
    public RunFreerails rf;
        
    /** Creates new form ProgressJPanel */
    public ProgressJPanel() {
        initComponents();
        
        FreerailsProgressMonitor pm = new FreerailsProgressMonitor(){
            public void setMessage(String s){
                smallTextJLabel.setText(s);
            }
            public void setValue(int i){
                jProgressBar1.setValue(i);
            }
            public void setMax(int max){
                jProgressBar1.setMaximum(max);
            }
        };        
        rf = new RunFreerails(pm);       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        bigTextJLabel = new javax.swing.JLabel();
        smallTextJLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setLayout(new java.awt.GridBagLayout());

        bigTextJLabel.setFont(new java.awt.Font("Dialog", 1, 24));
        bigTextJLabel.setText("Loading..");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(bigTextJLabel, gridBagConstraints);

        smallTextJLabel.setText("train graphics");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(smallTextJLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(jProgressBar1, gridBagConstraints);

    }//GEN-END:initComponents
    
    
    

    
    public void start(){
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bigTextJLabel;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel smallTextJLabel;
    // End of variables declaration//GEN-END:variables
    
}
