/*
 * TestJFrame.java
 *
 * Created on 30 August 2003, 22:15
 */

package jfreerails;

/**
 *
 * @author  Luke Lindsay
 */
public class RunFreerailsJFrame extends javax.swing.JFrame {
    
   
    
    /** Creates new form TestJFrame */
    public RunFreerailsJFrame() {
        initComponents();
       	
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        startUpOptionsJPanel1 = new jfreerails.StartUpOptionsJPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        getContentPane().add(startUpOptionsJPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        // Add your handling code here:
    }//GEN-LAST:event_formWindowIconified

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // Add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new RunFreerailsJFrame().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jfreerails.StartUpOptionsJPanel startUpOptionsJPanel1;
    // End of variables declaration//GEN-END:variables
    
}
