/*
 * StartUpOptionsJPanel.java
 *
 * Created on 30 August 2003, 22:41
 */

package jfreerails;

import java.awt.DisplayMode;

import javax.swing.JFrame;

import jfreerails.client.common.ScreenHandler;
import jfreerails.client.view.DisplayModesComboBoxModels;
import jfreerails.client.view.MyDisplayMode;
/**
 *
 * @author  Luke Lindsay
 */
public class StartUpOptionsJPanel extends javax.swing.JPanel {
    
    int mode = ScreenHandler.WINDOWED_MODE;
    
    DisplayMode selectedDisplayMode= null;
    
    int numberOfClients = 1;
    
    /** Creates new form StartUpOptionsJPanel */
    public StartUpOptionsJPanel() {
        initComponents();
		selectionChanged();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        displayOptions = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        startJButton = new javax.swing.JButton();
        displaymode = new javax.swing.JComboBox();
        numberOfClientsJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Windowed Mode");
        displayOptions.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jRadioButton1, gridBagConstraints);

        jRadioButton2.setText("Windowed Mode (fixed size 640x480)");
        displayOptions.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jRadioButton2, gridBagConstraints);

        jRadioButton3.setText("Fullscreen");
        displayOptions.add(jRadioButton3);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jRadioButton3, gridBagConstraints);

        startJButton.setText("Start");
        startJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startJButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(startJButton, gridBagConstraints);

        new DisplayModesComboBoxModels();
        displaymode.setModel(new DisplayModesComboBoxModels());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(displaymode, gridBagConstraints);

        numberOfClientsJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new Integer[] { new Integer(1), new Integer(2), new Integer(3), new Integer(4)   }));
        numberOfClientsJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfClientsJComboBoxActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(numberOfClientsJComboBox, gridBagConstraints);

        jLabel1.setText("Client(s)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel1, gridBagConstraints);

    }//GEN-END:initComponents

    private void numberOfClientsJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfClientsJComboBoxActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_numberOfClientsJComboBoxActionPerformed
    
    private void startJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startJButtonActionPerformed
        //disable all the controls        
        displaymode.setEnabled(false);
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
        jRadioButton3.setEnabled(false);
        numberOfClientsJComboBox.setEnabled(false);
        startJButton.setEnabled(false);        
        
        //Set selected options.
        selectedDisplayMode = ((MyDisplayMode)displaymode.getSelectedItem()).displayMode;
                
		Integer integer = (Integer)this.numberOfClientsJComboBox.getSelectedItem();
		this.numberOfClients= integer.intValue();
         
        RunFreerails rf = new RunFreerails();
        rf.setDisplayMode(this.selectedDisplayMode);
        rf.setNumberOfClients(this.numberOfClients);
        rf.setMode(this.mode);
        try{
        	Thread t = new Thread(rf);
            t.start();
        }catch (Exception e){
            e.printStackTrace();
        }   
		JFrame frame= (JFrame)this.getTopLevelAncestor();
		frame.dispose();
    }//GEN-LAST:event_startJButtonActionPerformed
    
    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // Add your handling code here:
        selectionChanged();
        mode = ScreenHandler.FULL_SCREEN;
      
    }//GEN-LAST:event_jRadioButton3ActionPerformed
    
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // Add your handling code here:
        selectionChanged();
        mode = ScreenHandler.FIXED_SIZE_WINDOWED_MODE;
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // Add your handling code here:
        selectionChanged();
        mode = ScreenHandler.WINDOWED_MODE;
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    
    public void selectionChanged(){
        if(jRadioButton3.isSelected()){
            displaymode.setEnabled(true);
            numberOfClientsJComboBox.setSelectedIndex(0);
            numberOfClientsJComboBox.setEnabled(false);
        }else{
            displaymode.setEnabled(false);
            numberOfClientsJComboBox.setEnabled(true);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup displayOptions;
    private javax.swing.JComboBox displaymode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JComboBox numberOfClientsJComboBox;
    private javax.swing.JButton startJButton;
    // End of variables declaration//GEN-END:variables
    
}
