/*
 * GameControlsJPanel.java
 *
 * Created on 19 April 2003, 16:41
 */

package jfreerails.client.view;
import jfreerails.world.top.World;
import jfreerails.client.renderer.ViewLists;
import java.awt.event.ActionListener;
/**
 *  This JPanel shows the games controls, that is, which keys do what.  Currently, it just displays
 *a hard coded html string.
 * @author  Luke
 */
public class GameControlsJPanel extends javax.swing.JPanel implements View {
    
    /** Creates new form GameControlsJPanel */
    public GameControlsJPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        done = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("<html>\n<h3>On the map view</h3>\n<table >\n<tr>\n    <td>Build Track</td>\n    <td>Mouse or number pad with Num Lock down</td>\n  </tr>\n  <tr>\n    <td>Build Station</td>\n    <td>'F8' (on existing track)</td>\n  </tr>\n  <tr>\n    <td>Build Train</td>\n    <td>'F7' (after building a station)</td>\n  </tr>\n <tr>\n    <td>Terrain Info</td>\n    <td>'I'</td>\n  </tr>\n  \n  </table>\n  \n<h3>On the train orders screen</h3>\n  <table>\n  <tr>\n    <td>Goto Station</td>\n    <td>'G'</td>\n  </tr>\n  <tr>\n    <td>Change station</td>\n    <td>'S'</td>\n  </tr>\n   <tr>\n    <td>Change consist</td>\n    <td>'C'</td>\n  </tr>\n</table>\n</html>");
        add(jLabel1);

        done.setText("Close");
        add(done);

    }//GEN-END:initComponents

    public void setup(World w, ViewLists vl, ActionListener submitButtonCallBack) {
        this.done.addActionListener(submitButtonCallBack);
    }    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
