/*
 * SelectEngineListCellRenderer.java
 *
 * Created on 25 December 2002, 17:44
 */

package jfreerails.client.view;

/**
 *
 * @author  lindsal8
 * 
 */
public class SelectEngineListCellRenderer extends javax.swing.JPanel {

    /** Creates new form SelectEngineListCellRenderer */
    public SelectEngineListCellRenderer() {
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        setLayout(new java.awt.BorderLayout());
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
