/*
 * TrainOrders.java
 *
 * Created on 30 March 2003, 02:00
 */

package jfreerails.client.view;
import java.awt.event.KeyEvent;
/**
 *
 * @author  Luke
 */
public class TrainOrders extends javax.swing.JPanel {
    
    private int[] consist = new int[0];
    
    private java.awt.Color oldBackground;
    
    private int field1;
    
    /** Creates new form TrainOrders */
    public TrainOrders() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        changeWaitUntilFullOrders = new javax.swing.JPopupMenu();
        wait = new javax.swing.JMenuItem();
        dontWait = new javax.swing.JMenuItem();
        changeStation = new javax.swing.JPopupMenu();
        bristol = new javax.swing.JMenuItem();
        london = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        removeStation = new javax.swing.JMenuItem();
        changeConsist = new javax.swing.JPopupMenu();
        mail = new javax.swing.JMenuItem();
        passenger = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        removeAll = new javax.swing.JMenuItem();
        orderNumber = new javax.swing.JLabel();
        waitUntilFullOrders = new javax.swing.JLabel();
        stationName = new javax.swing.JLabel();
        consistChange = new javax.swing.JLabel();

        wait.setText("Wait Unitl Full");
        wait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitActionPerformed(evt);
            }
        });

        changeWaitUntilFullOrders.add(wait);
        dontWait.setText("Don't Wait");
        dontWait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dontWaitActionPerformed(evt);
            }
        });

        changeWaitUntilFullOrders.add(dontWait);
        bristol.setText("Bristol");
        bristol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bristolActionPerformed(evt);
            }
        });

        changeStation.add(bristol);
        london.setText("Item");
        london.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                londonActionPerformed(evt);
            }
        });

        changeStation.add(london);
        changeStation.add(jSeparator1);
        removeStation.setText("Remove Station");
        changeStation.add(removeStation);
        mail.setText("Item");
        changeConsist.add(mail);
        passenger.setText("Item");
        changeConsist.add(passenger);
        changeConsist.add(jSeparator2);
        removeAll.setText("Remove All");
        changeConsist.add(removeAll);

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        setPreferredSize(new java.awt.Dimension(500, 26));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        orderNumber.setText("1.");
        orderNumber.setPreferredSize(new java.awt.Dimension(16, 16));
        add(orderNumber);

        waitUntilFullOrders.setText("W");
        waitUntilFullOrders.setToolTipText("Wait Until Full");
        waitUntilFullOrders.setPreferredSize(new java.awt.Dimension(16, 16));
        waitUntilFullOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                waitUntilFullOrdersMouseClicked(evt);
            }
        });

        add(waitUntilFullOrders);

        stationName.setText("Bristol Temple Meades");
        stationName.setPreferredSize(new java.awt.Dimension(200, 16));
        stationName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stationNameMouseClicked(evt);
            }
        });

        add(stationName);

        consistChange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consistChange.setText("no change");
        consistChange.setPreferredSize(new java.awt.Dimension(100, 16));
        consistChange.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        consistChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consistChangeMouseClicked(evt);
            }
        });

        add(consistChange);

    }//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // Add your handling code here:
        switch (evt.getKeyCode()){
            case KeyEvent.VK_O:
                this.changeWaitUntilFullOrders.show(this.waitUntilFullOrders, this.waitUntilFullOrders.getX(), this.waitUntilFullOrders.getY());
                break;
            case KeyEvent.VK_C:
                this.changeStation.show(this.stationName, this.stationName.getX(), this.stationName.getY());
                break;
            case KeyEvent.VK_UP:
                System.out.println("Up pressed");
                this.getParent().getParent().dispatchEvent(evt);
                break;
            case KeyEvent.VK_DOWN:
                System.out.println("Down pressed");
                this.getParent().getParent().dispatchEvent(evt);
                break;
                
        }
                
                
    }//GEN-LAST:event_formKeyPressed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // Add your handling code here:
        this.requestFocus();
    }//GEN-LAST:event_formMouseEntered

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // Add your handling code here:
         this.setBackground( this.oldBackground );
    }//GEN-LAST:event_formFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // Add your handling code here:
        this.oldBackground = this.getBackground();
        this.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_formFocusGained

    private void londonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_londonActionPerformed
        // Add your handling code here:
        this.stationName.setText("London");
    }//GEN-LAST:event_londonActionPerformed

    private void bristolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bristolActionPerformed
        // Add your handling code here:
        this.stationName.setText("Bristol");
    }//GEN-LAST:event_bristolActionPerformed

    private void dontWaitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dontWaitActionPerformed
        // Add your handling code here:
        this.waitUntilFullOrders.setText("-");
    }//GEN-LAST:event_dontWaitActionPerformed

    private void waitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitActionPerformed
        // Add your handling code here:
        this.waitUntilFullOrders.setText("W");
    }//GEN-LAST:event_waitActionPerformed

    private void consistChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consistChangeMouseClicked
        // Add your handling code here:
        System.out.println("Change consist");
        this.changeConsist.show(evt.getComponent(), evt.getX(), evt.getY());

    }//GEN-LAST:event_consistChangeMouseClicked

    private void stationNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stationNameMouseClicked
        // Add your handling code here:
        System.out.println("changeStation");
        this.changeStation.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_stationNameMouseClicked

    private void waitUntilFullOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_waitUntilFullOrdersMouseClicked
        // Add your handling code here:
        this.changeWaitUntilFullOrders.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_waitUntilFullOrdersMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu changeConsist;
    private javax.swing.JMenuItem london;
    private javax.swing.JPopupMenu changeStation;
    private javax.swing.JMenuItem removeStation;
    private javax.swing.JLabel stationName;
    private javax.swing.JLabel waitUntilFullOrders;
    private javax.swing.JMenuItem passenger;
    private javax.swing.JLabel consistChange;
    private javax.swing.JMenuItem bristol;
    private javax.swing.JMenuItem dontWait;
    private javax.swing.JMenuItem removeAll;
    private javax.swing.JMenuItem mail;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu changeWaitUntilFullOrders;
    private javax.swing.JLabel orderNumber;
    private javax.swing.JMenuItem wait;
    // End of variables declaration//GEN-END:variables
    
}
