package experimental;

import java.awt.Dimension;

import jfreerails.client.common.MyGlassPanel;
import jfreerails.client.top.JFrameMinimumSizeEnforcer;
import jfreerails.client.view.DialogueBoxController;
/**
 *
 * @author  lindsal8
 * 
 */
public class TestGlassPanelMethod extends javax.swing.JFrame {

  
   private  DialogueBoxController dialogueBoxController;
    
    /** Creates new form TestGlassPanelMethod */
    public TestGlassPanelMethod() {
         MyGlassPanel glassPanel = new MyGlassPanel();
         dialogueBoxController = new DialogueBoxController(glassPanel);
        initComponents ();
      
        this.setGlassPane(glassPanel);
        this.addComponentListener(new JFrameMinimumSizeEnforcer(640, 400));
        //pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jMenuBar1 = new javax.swing.JMenuBar();
        show = new javax.swing.JMenu();
        newspaper = new javax.swing.JMenuItem();
        selectEngine = new javax.swing.JMenuItem();
        selectWagons = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        
        show.setText("Newspaper");
          show.setText("Show");
          
          newspaper.setText("Newspaper");
            newspaper.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    newspaperActionPerformed(evt);
                }
            }
            );
            show.add(newspaper);
            
          selectEngine.setText("Select Engine");
            selectEngine.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    selectEngineActionPerformed(evt);
                }
            }
            );
            show.add(selectEngine);
            
          selectWagons.setText("Select Wagons");
            selectWagons.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    selectWagonsActionPerformed(evt);
                }
            }
            );
            show.add(selectWagons);
            jMenuBar1.add(show);
          addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        }
        );
        
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jfreerails/data/south_america.png")));
        
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);
        
        setJMenuBar(jMenuBar1);
        
    }//GEN-END:initComponents

  private void selectWagonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectWagonsActionPerformed
// Add your handling code here:
      dialogueBoxController.showSelectWagons();
  }//GEN-LAST:event_selectWagonsActionPerformed

  private void selectEngineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectEngineActionPerformed
// Add your handling code here:
      dialogueBoxController.showSelectEngine();
  }//GEN-LAST:event_selectEngineActionPerformed

  private void newspaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newspaperActionPerformed
// Add your handling code here:
      dialogueBoxController.showNewspaper("New headline!");
  }//GEN-LAST:event_newspaperActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        TestGlassPanelMethod test = new TestGlassPanelMethod ();
        test.setSize(new Dimension(640, 400));
        test.show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu show;
    private javax.swing.JMenuItem newspaper;
    private javax.swing.JMenuItem selectEngine;
    private javax.swing.JMenuItem selectWagons;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
